stages:
  - fetch
  - build
  - test

fetch:
  stage: fetch
  image: exaexa/blossom-builder
  script:
    - git submodule init; git submodule update
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

build:
  stage: build
  needs: [fetch]
  image: exaexa/blossom-builder
  script:
    - mkdir build; cd build; cmake ..; make install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'

test:
  stage: test
  needs: [build]
  image: exaexa/blossom-builder
  script:
    - /bin/true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
