stages:
  - fetch
  - build
  - test

fetch:
  stage: fetch
  image: exaexa/blossom-builder
  script:
    - git submodule init; git submodule update

build:
  stage: build
  needs: [fetch]
  image: exaexa/blossom-builder
  script:
    - mkdir build; cd build; cmake ..; make install

test:
  stage: test
  needs: [build]
  image: exaexa/blossom-builder
  script:
    - /bin/true
