# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch  
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch:
    runs-on: ubuntu-latest
    container: exaexa/blossom-builder
    steps:
      - run: git submodule init; git submodule update
      
  build:
    runs-on: ubuntu-latest
    needs: [fetch]
    container: exaexa/blossom-builder
    steps:
      - run: mkdir build; cd build; cmake ..; make install
      
  test:
    runs-on: ubuntu-latest
    needs: [build]
    container: exaexa/blossom-builder
    steps:
      - run: /bin/true
